extends: airbnb

env:
  browser: true
  node: true

rules:
  # Default rules
  comma-dangle:
    - 2
    - never
  indent:
    - 2
    - tab
  no-tabs: 0
  object-curly-newline: 0
  object-curly-spacing:
    - 2
    - always
    - objectsInObjects: false

  # Project-specific rules
  no-console: 0
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true  # ignore storybook-react
